run:
  timeout: 5m
  issue-exit-code: 0
  skip-tests: true
  build-tags:
    - linux
    - libsqlite3
    - sqlite_fts5
linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Other linters
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - durationcheck
    - gofmt
    - gosec
    - makezero
    - noctx
    - prealloc
    - unparam
linters-settings:
  gosimple:
    go: "1.19"
    checks: ["all"]
  gostatichcheck:
    go: "1.19"
    checks: ["all"]
  dupl:
    threshold: 125